name: 'KiCad Title Block Check'
author: 'jtmullen'
description: 'Check that the title block in KiCad Schematics and/or PCBs meet given requirements'
branding:
  icon: 'file-text'
  color: 'orange'
inputs:
  check_all:
    descripton: "Check all files instead of just those changed"
    required: false
    default: 'false'
  config_file:
    descripton: "Path to the config file, if not default"
    required: false
    default: '.github/title-blocks.yml' 
outputs:
  fails:
    description: "File(s) that failed, if run failed"
runs:
  using: 'docker'
  image: 'Dockerfile'
